### ISSUE TITLE
override commander special skills

### ISSUE THREAD

**Issue by swats-the-floran** [vcmi-mods/new-interface-mod#11]
incorrect
![image](https://github.com/vcmi-mods/new-interface-mod/assets/38055017/ee14a17c-a016-493f-8e0c-b49a8c3d06d2)

correct
![image](https://github.com/vcmi-mods/new-interface-mod/assets/38055017/d12d20a0-f12b-42f7-bc36-fd593f39de6c)
(Data/Zvx/Lib1.res/_mp_sp.bmp)

**Comment by misiokles** [comment]
Great job! Basically, this mod is abandonned, so feel free to upload new version with all your channges.

**Comment by swats-the-floran** [comment]
> Great job! Basically, this mod is abandonned, so feel free to upload new version with all your channges.

thanks. after this mod i will try to help with original interface (probably transition from .def buttons to json-png buttons).

**Comment by swats-the-floran** [comment]
as i can see - vcmi unified skills in stack and commander screens since commander's special skills already existed as different creatures' bonuses. unfortunate for modding but understandable. closed issue.
